### ISSUE TITLE
Serialize Poliqarps Alignment Operator

### ISSUE THREAD

**Issue by Akron** [KorAP/Koral#1]
At the moment, alignment is only defined by a list of class numbers, which may not be enough. For example
```
baum ^ {1:test}?
```
Isn't serializable at the moment, as the first class may not be part of the result. This should be fixed by having a more robust serialization mechanism.

This issue is moved from Trac (old number is #214)

**Comment by Akron** [comment]
I don't know if it's enough, but having an array of arrays of classes, with the alignment between, may be at least better, robust and shouldn't be too hard to deserialize.
```
"alignment":[[2,3],[4,5],[6,-1]]
```
Negative values can be used for boundaries (i.e. the [6,-1] example means, align to the right of class 6). Otherwise alignments are between classes, if there is no token between these classes. The alignment is either on the right (first value) or on the left (second value), if one of the classes is missing or -1.
I don't know if we can assume that there will be never more than 0 tokens between these class boundaries?

**Comment by jbingel** [comment]
I'm afraid I don't quite understand your suggested solution. Each array within the `alignments` array represents one alignment ruler, right? Then, is each such array composed of 2 values, as suggested by your examples? The first value denotes the class that is wrapped around the object that follows the alignment operator, correct? Please explain again: what does the second value do, and what happens if the class is not realised due to optionality?

Following your proposal, what would the example query from the initial post (`baum ^ {1:test}?`) look like?

**Comment by Akron** [comment]
The first value is the class of the object preceding the alignment ruler, the second value is the class of the object following the alignment ruler. If one class is missing (i.e. not found in the result), the other boundary is used.

For ```baum ^{1:test}?``` this would mean an internal serialization of ```{2:baum} ^ {1:test}?``` with
```
  "alignment":[[2,1]]
```

(There is no difference if the question mark is inside or outside the class.)

**Comment by jbingel** [comment]
Thanks! So the serialization will always just make sure the alignment operator is flanked by two classes (introducing new classes if necessary) and put those classes in the alignment array? Then if the alignment operator is at the very right of the query, the second value is -1. What if the alignment operator is the first object in the query, like `^ test`?

**Comment by Akron** [comment]
The first operator is -1.
It's not very elegant, but I guess it could be a workaround.

**Comment by jbingel** [comment]
Pushed to branch 'wip' (Commit ID c322c35).
